/* Automatic generated by './build/bin/build-entry.js' */

import Button from '../packages/button';
import Toast from '../packages/toast';
import Loading from '../packages/loading';
import MessageBox from '../packages/message-box';
import Alert from '../packages/alert';
import Confirm from '../packages/confirm';
import Actionsheet from '../packages/actionsheet';
import Icon from '../packages/icon';
import Spinner from '../packages/spinner';
import Group from '../packages/group';
import Cell from '../packages/cell';
import Sticky from '../packages/sticky';
import Grid from '../packages/grid';
import GridItem from '../packages/grid-item';
import Panel from '../packages/panel';
import Flex from '../packages/flex';
import FlexItem from '../packages/flex-item';
import DevicePlugin from 'sealui-m/src/plugins/device';
import TipsPlugin from 'sealui-m/src/plugins/tips';
import TitlePlugin from 'sealui-m/src/plugins/title';
import AjaxPlugin from 'sealui-m/src/plugins/ajax';
import TitleDirectives from 'sealui-m/src/directives/title';
const install = function(Vue) {
    /* istanbul ignore if */
  if (install.installed) return;
  Vue.component(Button.name, Button);
  Vue.component(Actionsheet.name, Actionsheet);
  Vue.component(Icon.name, Icon);
  Vue.component(Spinner.name, Spinner);
  Vue.component(Group.name, Group);
  Vue.component(Cell.name, Cell);
  Vue.component(Sticky.name, Sticky);
  Vue.component(Grid.name, Grid);
  Vue.component(GridItem.name, GridItem);
  Vue.component(Panel.name, Panel);
  Vue.component(Flex.name, Flex);
  Vue.component(FlexItem.name, FlexItem);

  Vue.$toast = Vue.prototype.$toast = Toast;
  Vue.$loading = Vue.prototype.$loading = Loading;
  Vue.$alert = Vue.prototype.$alert = Alert;
  Vue.$confirm = Vue.prototype.$confirm = Confirm;
  Vue.$actionsheet = Vue.prototype.$actionsheet = Actionsheet;
  Vue.$msgbox = Vue.prototype.$msgbox = MessageBox;

  Vue.use(DevicePlugin);
  Vue.use(TipsPlugin);
  Vue.use(TitlePlugin);
  Vue.use(AjaxPlugin);
  Vue.use(TitleDirectives);
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  install(window.Vue);
};

module.exports = {
  version: '0.0.1',
  install,
  Button,
  Toast,
  Loading,
  MessageBox,
  Alert,
  Confirm,
  Actionsheet,
  Icon,
  Spinner,
  Group,
  Cell,
  Sticky,
  Grid,
  GridItem,
  Panel,
  Flex,
  FlexItem
};
